services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgresDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: spring-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  pgdata: