spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect